### ISSUE TITLE
Content type "application/importmap+json" should not be enforced.

### ISSUE THREAD

**Issue by MilanKovacic** [single-spa/import-map-injector#11]
From my findings, this type is not yet accepted into standard types:

https://github.com/WICG/import-maps/issues/163
https://www.iana.org/assignments/media-types/media-types.xhtml

I propose removing this requirement.

**Comment by kfrederix** [comment]
I have opened [a PR](https://github.com/single-spa/import-map-injector/pull/13) to allow `application/json` as well, since I believe that most people are likely having their importmaps served as plain json today.

**Comment by internettrans** [comment]
The import-maps specification specifically requires the `application/json+importmap` mime type. See the following links:

https://github.com/WICG/import-maps?tab=readme-ov-file#installation
https://github.com/WICG/import-maps/issues/105

**Comment by kfrederix** [comment]
Hmm, interesting. I was not aware of that CSP concern... thanks.

**Comment by swanzeyb** [comment]
The standard makes no mention of requiring `application/json+importmap`. I've only found one[ third party article](https://www.honeybadger.io/blog/import-maps/) recommending it. I think this should not be enforced by import-map-injector. Let the browser enforce it if it's truly a standard.

**Comment by internettrans** [comment]
As far as I know, no major browsers currently support external import maps, but the spec included them for awhile before they were removed. See line of code below where `application/importmap+json` was required by the spec.

https://github.com/WICG/import-maps/blob/0071e99de999fecb56b89c0e65a34fa726f3fadb/spec.bs#L186
