### ISSUE TITLE
Documentation regarding "Asynchronous import map installation" is wrong.

### ISSUE THREAD

**Issue by MilanKovacic** [single-spa/import-map-injector#12]
In [Asynchronous import map installation](https://github.com/single-spa/import-map-injector#asynchronous-import-map-installation), usage is shown as:

`window.importMapInjector.importMapReady.then(() => {`

while the correct syntax is:

`window.importMapInjector.initPromise.then(() => {`

**Comment by kfrederix** [comment]
Hello, I noticed this as well and opened [this PR](https://github.com/single-spa/import-map-injector/pull/14) to adapt the doc.
